# Generated by Django 4.2 on 2025-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='nro_orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
