# Generated by Django 4.2 on 2025-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0002_technology_nro_orden_technology_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='nro_orden',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
