# Generated by Django 4.2 on 2025-02-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0003_alter_technology_nro_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('imagen', models.ImageField(upload_to='projects/')),
                ('nro_orden', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('inicio', models.DateField()),
                ('technologies', models.ManyToManyField(related_name='projects', to='app_mock.technology')),
            ],
        ),
    ]
