# Generated by Django 4.2 on 2025-02-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0005_remove_project_imagen_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='app_mock.trabajo')),
            ],
        ),
    ]
