# Generated by Django 4.2 on 2025-02-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0006_trabajo_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['-inicio']},
        ),
    ]
