# Generated by Django 4.2 on 2025-02-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0007_alter_puesto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='app_mock.academia')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
