# Generated by Django 4.2 on 2025-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mock', '0009_remove_academia_fin_remove_academia_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
